### ISSUE TITLE
Dependency fails to build under Erlang/OTP 20

### ISSUE THREAD

**Issue by cgregfreeman** [hansihe/rustler#104]
erlang_nif-sys v0.6.1 fails to build when the latest Erlang/OTP 20 is used. This worked fine under 19. 

Flagging here here as an issue to be aware of. 

https://github.com/goertzenator/erlang_nif-sys/issues/28

  ```
 Compiling void v1.0.2
   Compiling quote v0.3.15
   Compiling unicode-xid v0.0.4
   Compiling erlang_nif-sys v0.6.1
   Compiling lazy_static v0.1.16
   Compiling synom v0.11.3
   Compiling lazy_static v0.2.8
   Compiling unreachable v0.1.1
   Compiling syn v0.11.11
error: failed to run custom build command for `erlang_nif-sys v0.6.1`
process didn't exit successfully: `../debug/build/erlang_nif-sys-06da930bd64b6054/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.'../.cargo/registry/src/github.com-1ecc6299db9ec823/erlang_nif-sys-0.6.1/build.rs:28
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    lib/mix/tasks/compile.rustler.ex:58: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:12: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3

```

**Comment by nitingupta910** [comment]
erlang-nif-sys 0.6.2 is the version that supports OTP20. However, when I upgrade that to 0.6.2 and try to compile a nif module, I get this error:

```
error[E0063]: missing field `sizeof_ErlNifResourceTypeInit` in initializer of `erlang_nif_sys::erlang_nif_sys_api::ErlNifEntry`
  --> src/lib.rs:47:1
   |
47 | / rustler_export_nifs! {
48 | |     "Elixir.NifGraph",
49 | |     [("add", 2, add),
50 | |      ("open", 1, open),
...  |
55 | |     None
56 | | }
   | |_^ missing `sizeof_ErlNifResourceTypeInit`
   |
   = note: this error originates in a macro outside of the current crate

error: aborting due to previous error
```

The field ```sizeof_ErlNifResourceTypeInit``` has been added to erlang_nif-sys in this commit:

```
https://github.com/goertzenator/erlang_nif-sys/commit/ec4d911e25476a3f6f39d6710672afc4f464d41e
```

**Comment by cgregfreeman** [comment]
This has been resolved with rustler 0.15.1. Thank you @hansihe !

Do the following if you have existing code:
mix deps.clean rustler
Update cargo.toml to use 0.15.1 instead of 0.14.x
mix deps.get
mix 

I got this to successfully build an existing project that was previously failing after the OTP 20 upgrade.
